(cl:defpackage compsci403_assignment1-srv
  (:use )
  (:export
   "ASSIGNMENT1CALLERSRV"
   "<ASSIGNMENT1CALLERSRV-REQUEST>"
   "ASSIGNMENT1CALLERSRV-REQUEST"
   "<ASSIGNMENT1CALLERSRV-RESPONSE>"
   "ASSIGNMENT1CALLERSRV-RESPONSE"
   "ASSIGNMENT1PROVIDERSRV"
   "<ASSIGNMENT1PROVIDERSRV-REQUEST>"
   "ASSIGNMENT1PROVIDERSRV-REQUEST"
   "<ASSIGNMENT1PROVIDERSRV-RESPONSE>"
   "ASSIGNMENT1PROVIDERSRV-RESPONSE"
  ))

