/* Auto-generated by genmsg_cpp for file /home/wyliao/Desktop/compsci403_assignment6/srv/BuildRRTSrv.srv */
#ifndef COMPSCI403_ASSIGNMENT6_SERVICE_BUILDRRTSRV_H
#define COMPSCI403_ASSIGNMENT6_SERVICE_BUILDRRTSRV_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"



#include "compsci403_assignment6/RRTNode.h"

namespace compsci403_assignment6
{
template <class ContainerAllocator>
struct BuildRRTSrvRequest_ {
  typedef BuildRRTSrvRequest_<ContainerAllocator> Type;

  BuildRRTSrvRequest_()
  {
  }

  BuildRRTSrvRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::compsci403_assignment6::BuildRRTSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::compsci403_assignment6::BuildRRTSrvRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct BuildRRTSrvRequest
typedef  ::compsci403_assignment6::BuildRRTSrvRequest_<std::allocator<void> > BuildRRTSrvRequest;

typedef boost::shared_ptr< ::compsci403_assignment6::BuildRRTSrvRequest> BuildRRTSrvRequestPtr;
typedef boost::shared_ptr< ::compsci403_assignment6::BuildRRTSrvRequest const> BuildRRTSrvRequestConstPtr;



template <class ContainerAllocator>
struct BuildRRTSrvResponse_ {
  typedef BuildRRTSrvResponse_<ContainerAllocator> Type;

  BuildRRTSrvResponse_()
  : rrt()
  {
  }

  BuildRRTSrvResponse_(const ContainerAllocator& _alloc)
  : rrt(_alloc)
  {
  }

  typedef std::vector< ::compsci403_assignment6::RRTNode_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::compsci403_assignment6::RRTNode_<ContainerAllocator> >::other >  _rrt_type;
  std::vector< ::compsci403_assignment6::RRTNode_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::compsci403_assignment6::RRTNode_<ContainerAllocator> >::other >  rrt;


  typedef boost::shared_ptr< ::compsci403_assignment6::BuildRRTSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::compsci403_assignment6::BuildRRTSrvResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct BuildRRTSrvResponse
typedef  ::compsci403_assignment6::BuildRRTSrvResponse_<std::allocator<void> > BuildRRTSrvResponse;

typedef boost::shared_ptr< ::compsci403_assignment6::BuildRRTSrvResponse> BuildRRTSrvResponsePtr;
typedef boost::shared_ptr< ::compsci403_assignment6::BuildRRTSrvResponse const> BuildRRTSrvResponseConstPtr;


struct BuildRRTSrv
{

typedef BuildRRTSrvRequest Request;
typedef BuildRRTSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct BuildRRTSrv
} // namespace compsci403_assignment6

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::compsci403_assignment6::BuildRRTSrvRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::compsci403_assignment6::BuildRRTSrvRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::compsci403_assignment6::BuildRRTSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::compsci403_assignment6::BuildRRTSrvRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::compsci403_assignment6::BuildRRTSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compsci403_assignment6/BuildRRTSrvRequest";
  }

  static const char* value(const  ::compsci403_assignment6::BuildRRTSrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::compsci403_assignment6::BuildRRTSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::compsci403_assignment6::BuildRRTSrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::compsci403_assignment6::BuildRRTSrvRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::compsci403_assignment6::BuildRRTSrvResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::compsci403_assignment6::BuildRRTSrvResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::compsci403_assignment6::BuildRRTSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9680cc06ea3c47eb5a92d56793715529";
  }

  static const char* value(const  ::compsci403_assignment6::BuildRRTSrvResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x9680cc06ea3c47ebULL;
  static const uint64_t static_value2 = 0x5a92d56793715529ULL;
};

template<class ContainerAllocator>
struct DataType< ::compsci403_assignment6::BuildRRTSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compsci403_assignment6/BuildRRTSrvResponse";
  }

  static const char* value(const  ::compsci403_assignment6::BuildRRTSrvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::compsci403_assignment6::BuildRRTSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
RRTNode[] rrt\n\
\n\
\n\
================================================================================\n\
MSG: compsci403_assignment6/RRTNode\n\
# Location of the tree node.\n\
geometry_msgs/Point location\n\
\n\
# Index of parent node, -1 if there is no parent (root node).\n\
int32 parent\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
";
  }

  static const char* value(const  ::compsci403_assignment6::BuildRRTSrvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::compsci403_assignment6::BuildRRTSrvRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct BuildRRTSrvRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::compsci403_assignment6::BuildRRTSrvResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.rrt);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct BuildRRTSrvResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<compsci403_assignment6::BuildRRTSrv> {
  static const char* value() 
  {
    return "9680cc06ea3c47eb5a92d56793715529";
  }

  static const char* value(const compsci403_assignment6::BuildRRTSrv&) { return value(); } 
};

template<>
struct DataType<compsci403_assignment6::BuildRRTSrv> {
  static const char* value() 
  {
    return "compsci403_assignment6/BuildRRTSrv";
  }

  static const char* value(const compsci403_assignment6::BuildRRTSrv&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<compsci403_assignment6::BuildRRTSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9680cc06ea3c47eb5a92d56793715529";
  }

  static const char* value(const compsci403_assignment6::BuildRRTSrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<compsci403_assignment6::BuildRRTSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compsci403_assignment6/BuildRRTSrv";
  }

  static const char* value(const compsci403_assignment6::BuildRRTSrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<compsci403_assignment6::BuildRRTSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9680cc06ea3c47eb5a92d56793715529";
  }

  static const char* value(const compsci403_assignment6::BuildRRTSrvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<compsci403_assignment6::BuildRRTSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compsci403_assignment6/BuildRRTSrv";
  }

  static const char* value(const compsci403_assignment6::BuildRRTSrvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // COMPSCI403_ASSIGNMENT6_SERVICE_BUILDRRTSRV_H

