/* Auto-generated by genmsg_cpp for file /home/wyliao/Desktop/compsci403_assignment6/srv/RandomConfigSrv.srv */
#ifndef COMPSCI403_ASSIGNMENT6_SERVICE_RANDOMCONFIGSRV_H
#define COMPSCI403_ASSIGNMENT6_SERVICE_RANDOMCONFIGSRV_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"



#include "geometry_msgs/Point.h"

namespace compsci403_assignment6
{
template <class ContainerAllocator>
struct RandomConfigSrvRequest_ {
  typedef RandomConfigSrvRequest_<ContainerAllocator> Type;

  RandomConfigSrvRequest_()
  {
  }

  RandomConfigSrvRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::compsci403_assignment6::RandomConfigSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::compsci403_assignment6::RandomConfigSrvRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct RandomConfigSrvRequest
typedef  ::compsci403_assignment6::RandomConfigSrvRequest_<std::allocator<void> > RandomConfigSrvRequest;

typedef boost::shared_ptr< ::compsci403_assignment6::RandomConfigSrvRequest> RandomConfigSrvRequestPtr;
typedef boost::shared_ptr< ::compsci403_assignment6::RandomConfigSrvRequest const> RandomConfigSrvRequestConstPtr;



template <class ContainerAllocator>
struct RandomConfigSrvResponse_ {
  typedef RandomConfigSrvResponse_<ContainerAllocator> Type;

  RandomConfigSrvResponse_()
  : q_rand()
  {
  }

  RandomConfigSrvResponse_(const ContainerAllocator& _alloc)
  : q_rand(_alloc)
  {
  }

  typedef  ::geometry_msgs::Point_<ContainerAllocator>  _q_rand_type;
   ::geometry_msgs::Point_<ContainerAllocator>  q_rand;


  typedef boost::shared_ptr< ::compsci403_assignment6::RandomConfigSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::compsci403_assignment6::RandomConfigSrvResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct RandomConfigSrvResponse
typedef  ::compsci403_assignment6::RandomConfigSrvResponse_<std::allocator<void> > RandomConfigSrvResponse;

typedef boost::shared_ptr< ::compsci403_assignment6::RandomConfigSrvResponse> RandomConfigSrvResponsePtr;
typedef boost::shared_ptr< ::compsci403_assignment6::RandomConfigSrvResponse const> RandomConfigSrvResponseConstPtr;


struct RandomConfigSrv
{

typedef RandomConfigSrvRequest Request;
typedef RandomConfigSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct RandomConfigSrv
} // namespace compsci403_assignment6

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::compsci403_assignment6::RandomConfigSrvRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::compsci403_assignment6::RandomConfigSrvRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::compsci403_assignment6::RandomConfigSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::compsci403_assignment6::RandomConfigSrvRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::compsci403_assignment6::RandomConfigSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compsci403_assignment6/RandomConfigSrvRequest";
  }

  static const char* value(const  ::compsci403_assignment6::RandomConfigSrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::compsci403_assignment6::RandomConfigSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::compsci403_assignment6::RandomConfigSrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::compsci403_assignment6::RandomConfigSrvRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::compsci403_assignment6::RandomConfigSrvResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::compsci403_assignment6::RandomConfigSrvResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::compsci403_assignment6::RandomConfigSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ebedd2ab5ada3637b4212236735875be";
  }

  static const char* value(const  ::compsci403_assignment6::RandomConfigSrvResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xebedd2ab5ada3637ULL;
  static const uint64_t static_value2 = 0xb4212236735875beULL;
};

template<class ContainerAllocator>
struct DataType< ::compsci403_assignment6::RandomConfigSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compsci403_assignment6/RandomConfigSrvResponse";
  }

  static const char* value(const  ::compsci403_assignment6::RandomConfigSrvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::compsci403_assignment6::RandomConfigSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "geometry_msgs/Point q_rand\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
";
  }

  static const char* value(const  ::compsci403_assignment6::RandomConfigSrvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::compsci403_assignment6::RandomConfigSrvResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::compsci403_assignment6::RandomConfigSrvRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct RandomConfigSrvRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::compsci403_assignment6::RandomConfigSrvResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.q_rand);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct RandomConfigSrvResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<compsci403_assignment6::RandomConfigSrv> {
  static const char* value() 
  {
    return "ebedd2ab5ada3637b4212236735875be";
  }

  static const char* value(const compsci403_assignment6::RandomConfigSrv&) { return value(); } 
};

template<>
struct DataType<compsci403_assignment6::RandomConfigSrv> {
  static const char* value() 
  {
    return "compsci403_assignment6/RandomConfigSrv";
  }

  static const char* value(const compsci403_assignment6::RandomConfigSrv&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<compsci403_assignment6::RandomConfigSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ebedd2ab5ada3637b4212236735875be";
  }

  static const char* value(const compsci403_assignment6::RandomConfigSrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<compsci403_assignment6::RandomConfigSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compsci403_assignment6/RandomConfigSrv";
  }

  static const char* value(const compsci403_assignment6::RandomConfigSrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<compsci403_assignment6::RandomConfigSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ebedd2ab5ada3637b4212236735875be";
  }

  static const char* value(const compsci403_assignment6::RandomConfigSrvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<compsci403_assignment6::RandomConfigSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compsci403_assignment6/RandomConfigSrv";
  }

  static const char* value(const compsci403_assignment6::RandomConfigSrvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // COMPSCI403_ASSIGNMENT6_SERVICE_RANDOMCONFIGSRV_H

