/* Auto-generated by genmsg_cpp for file /home/wyliao/Desktop/compsci403_assignment1/srv/Assignment1CallerSrv.srv */
#ifndef COMPSCI403_ASSIGNMENT1_SERVICE_ASSIGNMENT1CALLERSRV_H
#define COMPSCI403_ASSIGNMENT1_SERVICE_ASSIGNMENT1CALLERSRV_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace compsci403_assignment1
{
template <class ContainerAllocator>
struct Assignment1CallerSrvRequest_ {
  typedef Assignment1CallerSrvRequest_<ContainerAllocator> Type;

  Assignment1CallerSrvRequest_()
  {
  }

  Assignment1CallerSrvRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::compsci403_assignment1::Assignment1CallerSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::compsci403_assignment1::Assignment1CallerSrvRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct Assignment1CallerSrvRequest
typedef  ::compsci403_assignment1::Assignment1CallerSrvRequest_<std::allocator<void> > Assignment1CallerSrvRequest;

typedef boost::shared_ptr< ::compsci403_assignment1::Assignment1CallerSrvRequest> Assignment1CallerSrvRequestPtr;
typedef boost::shared_ptr< ::compsci403_assignment1::Assignment1CallerSrvRequest const> Assignment1CallerSrvRequestConstPtr;



template <class ContainerAllocator>
struct Assignment1CallerSrvResponse_ {
  typedef Assignment1CallerSrvResponse_<ContainerAllocator> Type;

  Assignment1CallerSrvResponse_()
  : str()
  {
  }

  Assignment1CallerSrvResponse_(const ContainerAllocator& _alloc)
  : str(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _str_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  str;


  typedef boost::shared_ptr< ::compsci403_assignment1::Assignment1CallerSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::compsci403_assignment1::Assignment1CallerSrvResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct Assignment1CallerSrvResponse
typedef  ::compsci403_assignment1::Assignment1CallerSrvResponse_<std::allocator<void> > Assignment1CallerSrvResponse;

typedef boost::shared_ptr< ::compsci403_assignment1::Assignment1CallerSrvResponse> Assignment1CallerSrvResponsePtr;
typedef boost::shared_ptr< ::compsci403_assignment1::Assignment1CallerSrvResponse const> Assignment1CallerSrvResponseConstPtr;


struct Assignment1CallerSrv
{

typedef Assignment1CallerSrvRequest Request;
typedef Assignment1CallerSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct Assignment1CallerSrv
} // namespace compsci403_assignment1

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::compsci403_assignment1::Assignment1CallerSrvRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::compsci403_assignment1::Assignment1CallerSrvRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::compsci403_assignment1::Assignment1CallerSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::compsci403_assignment1::Assignment1CallerSrvRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::compsci403_assignment1::Assignment1CallerSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compsci403_assignment1/Assignment1CallerSrvRequest";
  }

  static const char* value(const  ::compsci403_assignment1::Assignment1CallerSrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::compsci403_assignment1::Assignment1CallerSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::compsci403_assignment1::Assignment1CallerSrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::compsci403_assignment1::Assignment1CallerSrvRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::compsci403_assignment1::Assignment1CallerSrvResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::compsci403_assignment1::Assignment1CallerSrvResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::compsci403_assignment1::Assignment1CallerSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "994972b6e03928b2476860ce6c4c8e17";
  }

  static const char* value(const  ::compsci403_assignment1::Assignment1CallerSrvResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x994972b6e03928b2ULL;
  static const uint64_t static_value2 = 0x476860ce6c4c8e17ULL;
};

template<class ContainerAllocator>
struct DataType< ::compsci403_assignment1::Assignment1CallerSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compsci403_assignment1/Assignment1CallerSrvResponse";
  }

  static const char* value(const  ::compsci403_assignment1::Assignment1CallerSrvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::compsci403_assignment1::Assignment1CallerSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string str\n\
\n\
\n\
";
  }

  static const char* value(const  ::compsci403_assignment1::Assignment1CallerSrvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::compsci403_assignment1::Assignment1CallerSrvRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct Assignment1CallerSrvRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::compsci403_assignment1::Assignment1CallerSrvResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.str);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct Assignment1CallerSrvResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<compsci403_assignment1::Assignment1CallerSrv> {
  static const char* value() 
  {
    return "994972b6e03928b2476860ce6c4c8e17";
  }

  static const char* value(const compsci403_assignment1::Assignment1CallerSrv&) { return value(); } 
};

template<>
struct DataType<compsci403_assignment1::Assignment1CallerSrv> {
  static const char* value() 
  {
    return "compsci403_assignment1/Assignment1CallerSrv";
  }

  static const char* value(const compsci403_assignment1::Assignment1CallerSrv&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<compsci403_assignment1::Assignment1CallerSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "994972b6e03928b2476860ce6c4c8e17";
  }

  static const char* value(const compsci403_assignment1::Assignment1CallerSrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<compsci403_assignment1::Assignment1CallerSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compsci403_assignment1/Assignment1CallerSrv";
  }

  static const char* value(const compsci403_assignment1::Assignment1CallerSrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<compsci403_assignment1::Assignment1CallerSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "994972b6e03928b2476860ce6c4c8e17";
  }

  static const char* value(const compsci403_assignment1::Assignment1CallerSrvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<compsci403_assignment1::Assignment1CallerSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compsci403_assignment1/Assignment1CallerSrv";
  }

  static const char* value(const compsci403_assignment1::Assignment1CallerSrvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // COMPSCI403_ASSIGNMENT1_SERVICE_ASSIGNMENT1CALLERSRV_H

